### ISSUE TITLE
Error on fresh install

### ISSUE THREAD

**Issue by jandudulski** [monterail/sanelint#3]
Error: obsolete parameter AlignWith (for Lint/EndAlignment) found in /path/to/.rubocop.yml
    `AlignWith` has been renamed to `EnforcedStyleAlignWith`

**Comment by RadoMark** [comment]
@jandudulski can we close this issue?

**Comment by jandudulski** [comment]
Sorry. That was my mistake 😳

**Comment by olleicua** [comment]
What is the status of this?
